In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('satgpa.csv')
df.insert(loc=0, column='ones', value=1) #Agregamos la columna de unos
df.drop(['sat_v', 'sat_m'], axis=1, inplace=True)
df.head()
# Dejamos solo las columnas de interés que son: sexo, total de percentil de SAT verbal y matemática, y el promedio GPA en highschool

ones  sex  sat_sum  hs_gpa  fy_gpa
0     1    1      127    3.40    3.18
1     1    2      122    4.00    3.33
2     1    2      116    3.75    3.25
3     1    1       95    3.75    2.42
4     1    1      107    4.00    2.63

In [3]:
y_column = df.pop('fy_gpa').to_numpy().reshape(1000,1)
x_columns = df.to_numpy()

In [4]:
x_columns

array([[  1.  ,   1.  , 127.  ,   3.4 ],
       [  1.  ,   2.  , 122.  ,   4.  ],
       [  1.  ,   2.  , 116.  ,   3.75],
       ...,
       [  1.  ,   1.  , 114.  ,   3.5 ],
       [  1.  ,   1.  , 120.  ,   2.3 ],
       [  1.  ,   1.  ,  93.  ,   2.7 ]])

In [5]:
m, n = x_columns.shape

In [6]:
x_columns.shape

(1000, 4)

In [7]:
random_theta = np.random.rand(n,1)
random_theta

array([[0.58284234],
       [0.56046328],
       [0.26890819],
       [0.87012363]])

In [8]:
def linear_function_grades(X, y, theta):
    h = X @ theta
    return ((y - h) ** 2).sum() / (2 * len(X))

def linear_gradient_grades(X, y, theta):
    h = X @ theta
    return (X.T @ (h - y)) / len(X)

def gradient_descent_grades(X, y, theta_0, linear_function, linear_gradient, learning_rate=0.0001, threshold= 0.001, max_iter=1000):
    theta = theta_0
    iteration = 0
    grades = []

    while np.linalg.norm(linear_gradient(X, y, theta)) > threshold and iteration < max_iter:
        iteration += 1
        theta = theta - learning_rate * linear_gradient(X, y, theta)
        grades.append(linear_function(X, y, theta))
    return theta

In [16]:
theta_results1 = gradient_descent_grades(x_columns, y_column, random_theta, linear_function_grades, linear_gradient_grades)
theta_results1

array([[ 0.57450674],
       [ 0.53309581],
       [-0.01489237],
       [ 0.84321739]])

In [29]:
def gradient_descent_grades(X, y, theta_0, linear_function, linear_gradient, learning_rate=0.0001, threshold= 0.5, max_iter=1000):
    theta = theta_0
    iteration = 0
    grades = []

    while np.linalg.norm(linear_gradient(X, y, theta)) > threshold and iteration < max_iter:
        iteration += 1
        theta = theta - learning_rate * linear_gradient(X, y, theta)
        grades.append(linear_function(X, y, theta))
    return theta
    
theta_results2 = gradient_descent_grades(x_columns, y_column, random_theta, linear_function_grades, linear_gradient_grades)
theta_results2

array([[4.79495083e-01],
       [9.90473528e-01],
       [6.15355716e-06],
       [1.79079867e-01]])

In [62]:
def gradient_descent_grades(X, y, theta_0, linear_function, linear_gradient, learning_rate=0.0001, threshold= 2, max_iter=1000):
    theta = theta_0
    iteration = 0
    grades = []

    while np.linalg.norm(linear_gradient(X, y, theta)) > threshold and iteration < max_iter:
        iteration += 1
        theta = theta - learning_rate * linear_gradient(X, y, theta)
        grades.append(linear_function(X, y, theta))
    return theta
    
theta_results3 = gradient_descent_grades(x_columns, y_column, random_theta, linear_function_grades, linear_gradient_grades)
theta_results3

array([[ 0.58011563],
       [ 0.55638711],
       [-0.01580823],
       [ 0.8613148 ]])