In [14]:
import pandas as pd 
import numpy as np
import matplotlib as plt

In [28]:
df = pd.read_csv('satgpa.csv')
df.insert(loc=0, column='ones', value=1) #Agregamos la columna de unos
df.drop(['sat_v', 'sat_m'], axis=1, inplace=True)
df.head()
# Dejamos solo las columnas de interés que son: sexo, total de percentil de SAT verbal y matemática, y el promedio GPA en highschool

ones  sex  sat_sum  hs_gpa  fy_gpa
0     1    1      127    3.40    3.18
1     1    2      122    4.00    3.33
2     1    2      116    3.75    3.25
3     1    1       95    3.75    2.42
4     1    1      107    4.00    2.63

In [29]:
y_column = df.pop('fy_gpa').to_numpy().reshape(1000,1)
x_columns = df.to_numpy()

In [30]:
x_columns

array([[  1.  ,   1.  , 127.  ,   3.4 ],
       [  1.  ,   2.  , 122.  ,   4.  ],
       [  1.  ,   2.  , 116.  ,   3.75],
       ...,
       [  1.  ,   1.  , 114.  ,   3.5 ],
       [  1.  ,   1.  , 120.  ,   2.3 ],
       [  1.  ,   1.  ,  93.  ,   2.7 ]])

In [32]:
m, n = x_columns.shape

In [33]:
x_columns.shape

(1000, 4)

In [34]:
random_theta = np.random.rand(n,1)
random_theta

array([[0.913242  ],
       [0.74324086],
       [0.99245795],
       [0.64534083]])

In [35]:
def linear_function_grades(X, y, theta):
    h = X @ theta
    return ((y - h) ** 2).sum() / (2 * len(X))

def linear_gradient_grades(X, y, theta):
    h = X @ theta
    return (X.T @ (h - y)) / len(X)

def gradient_descent_grades(X, y, theta_0, linear_function, linear_gradient, learning_rate=0.0001, threshold= 0.001, max_iter=1000):
    theta = theta_0
    iteration = 0
    grades = []

    while np.linalg.norm(linear_gradient(X, y, theta)) > threshold and iteration < max_iter:
        iteration += 1
        theta = theta - learning_rate * linear_gradient(X, y, theta)
        grades.append(linear_function(X, y, theta))
    return theta, theta.shape

In [36]:
print(gradient_descent_grades(x_columns, y_column, random_theta, linear_function_grades, linear_gradient_grades))

(array([[ 0.89746839],
       [ 0.70183951],
       [-0.01286547],
       [ 0.60026803]]), (4, 1))
